### ISSUE TITLE
Big Sur support?

### ISSUE THREAD

**Issue by karlhorky** [markhughes/MiddleTap#2]
Hi, thanks for this fork!

Would you be able to offer a version that works on the new macOS Big Sur?

The existing [`artginzburg/MiddleClick-Catalina`](https://github.com/artginzburg/MiddleClick-Catalina) does not appear to work anymore: https://twitter.com/karlhorky/status/1327192793115193345

**Comment by karlhorky** [comment]
Maybe it has something to do with the private framework `MultitouchSupport` being at a different path in Big Sur: https://developer.apple.com/forums/thread/653972

**Comment by karlhorky** [comment]
@artginzburg, @LoPablo, @cl3m or @rmhsilva, would any of you be able to weigh in on the possible incompatibility here?

I could even see foreseeably taking over the work myself, if I was pointed in the right direction and guided a bit (I'm a beginner with Objective-C development).

**Comment by LoPablo** [comment]
I am actually no longer using MiddleClick/MiddleTap. I first switched to the Mutlitouch App and after that I just got used to using the context menu when right clicking. If there is some time left I might take a look at why this is nor longer working on Big Sur but I can't promise.

**Comment by karlhorky** [comment]
That would be great if you have time, thanks! I was researching a bit what possible incompatibilities could be and I stumbled across the path change for the private `MultitouchSupport` framework that I mentioned above in https://github.com/markhughes/MiddleTap/issues/2#issuecomment-729733099.

According to https://github.com/EpicGames/UnrealEngine/commit/1d252ee345cdf6c232b20c3b4bf14f13bb569c9d, the new path can be resolved as such:

```
string SDKROOT = Utils.RunLocalProcessAndReturnStdOut("/usr/bin/xcrun", "--sdk macosx --show-sdk-path");
PublicAdditionalLibraries.Add(SDKROOT + "/System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/Current/MultitouchSupport.tbd");
```

...which for me results in a change between the two paths like this:

```diff
-/System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/Current/MultitouchSupport
+/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/Current/MultitouchSupport.tbd
```

**Comment by LoPablo** [comment]
So i just cloned this repo. It builds without any issues and tap and click functionality ist working
Since MiddleClick Catalina ist archived, is there anything that is not working with this fork? I didn't follow any development after my work for restoring the click mechanism was forked off.

**Comment by LoPablo** [comment]
Does the binary you run show any error? Do you get a build error? 
Btw: My magic mouse is dying. Poor thing.

**Comment by karlhorky** [comment]
> Since MiddleClick Catalina ist archived, is there anything that is not working with this fork?

Hm, no, there should be no difference for this fork (just the readme update in https://github.com/markhughes/MiddleTap/commit/f7b2bd3269aa31d935a5892fa2a291890fe7048e)

> Does the binary you run show any error? Do you get a build error?

What I have been trying is the `midclick` from Homebrew (`v2.4.5`):

```
$ brew cask info midclick
midclick: 2.4.5
https://github.com/DaFuqtor/MiddleClick
/usr/local/Caskroom/midclick/2.4.5 (64B)
==> Name
MiddleClick
==> Description
None
==> Artifacts
MiddleClick.app (App)
```

**Comment by karlhorky** [comment]
Oh wait, the latest version of this `midclick` cask seems to be outdated! 🤦‍♂️🤦‍♂️

There is another cask called `middleclick` with the updated [`v2.4.8.1`](https://github.com/artginzburg/MiddleClick-Catalina/releases/tag/2.4.8.1), which seems to be the latest version of [`artginzburg/MiddleClick-Catalina`](https://github.com/artginzburg/MiddleClick-Catalina):

```bash
$ brew cask info middleclick
middleclick: 2.4.8.1
https://github.com/DaFuqtor/MiddleClick
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/middleclick.rb
==> Name
MiddleClick
==> Description
None
==> Artifacts
MiddleClick.app (App)
==> Caveats
middleclick has been officially discontinued upstream.
It may stop working correctly (or at all) in recent versions of macOS.

==> Analytics
install: 205 (30 days), 532 (90 days), 3,138 (365 days)
```

Just installed (and enabled in System Preferences -> Security -> Privacy -> Accessibility) and it's working!

Thanks for all the help @LoPablo and sorry for the confusion!!

**Comment by karlhorky** [comment]
And now there's a version in Lua based off of this code in [Hammerspoon](http://www.hammerspoon.org/) thanks to **asmagill** ([issue here](https://github.com/Hammerspoon/hammerspoon/issues/2057)):

https://github.com/asmagill/hs._asm.undocumented.touchdevice/blob/master/Examples/middleButton.lua
